---
title: "Desk Usage"
output: 
  flexdashboard::flex_dashboard

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

list_of_packages <- c("dplyr", "tidyverse", "flexdashboard", "scales", "here")

new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages, repos = "https://cloud.r-project.org/")

#Load required packages
lapply(list_of_packages, library, character.only = TRUE)
```


```{r summary_stats, echo=FALSE}
attendance <- read.csv(here("/data/Problem 3 Desk Usage/attendance.csv"))
desks <-  read.csv(here("/data/Problem 3 Desk Usage/desks.csv"))
people <- read.csv(here("data/Problem 3 Desk Usage/people.csv"))

#Attendance - convert to date
attendance$Date <- as.Date(attendance$Date, "%d/%m/%Y")

#Assign visitors to the Unassigned team
levels(attendance$Team) <- c(levels(attendance$Team), "Unassigned") 
attendance$Team[attendance$Visitor_Flag=="Yes"] <- "Unassigned"

#Total number of desks in the building
desk_total <- as.vector(count(desks))
#Total number of staff
staff_total <- count(people)
#Total number of teams
teams_total <- desks %>%
	group_by(Team) %>%
	summarise(staff = n())%>%
	summarise(staff = n())

#Unique visitors to the building in 
unique_visitors_per_year <-   filter(attendance, Visitor_Flag == "Yes") %>%
	group_by(Username) %>%
	summarise(count = n()) %>%
	summarise(count = n()) 


# utilisation of the building by day
utilisation_by_day <- attendance %>%
  group_by(Date) %>%
  summarise(count = n())

#Desk utilistation annually
toal_utilised_desks_annual <- sum(utilisation_by_day$count)
total_available_desks_annual <- nrow(desks) * nrow(utilisation_by_day)
total_unused_desks_annual <- total_available_desks_annual - toal_utilised_desks_annual

#Desk utilisation daily
max_utilisation<- top_n(utilisation_by_day, 1, utilisation_by_day$count)
max_utilisation_date = max_utilisation$Date
max_utilisation_perc <- round((max_utilisation$count / desk_total$n) * 100, 0)
  
#Heatmap Data
attendance_by_date_team <- attendance %>%
  group_by(Date, Team) %>%
  summarise(count = n())

#Get team desk allocation
team_desk_allocation <- desks %>%
	group_by(Team) %>%
	summarise(daily_alocation = n())

#Join data
heatmap_data <- merge(x = attendance_by_date_team, y = team_desk_allocation, by = "Team", all.x = TRUE)

#replace na with zero
heatmap_data[is.na(heatmap_data)] <- 0

#Calculate weekday
heatmap_data$day <- weekdays(as.Date(heatmap_data$Date))

#Calculate teams daily usage based on allocation
heatmap_data$team_util_perc <- round((heatmap_data$count / heatmap_data$daily_alocation ) * 100, digits = 0)
heatmap_data$team_util_perc[heatmap_data$daily_alocation==0] <- 101

#Transpose data to make a table for the heatmap
drops <- c("count","daily_alocation", "day")
heatmap_data <- heatmap_data[ , !(names(heatmap_data) %in% drops)]

heatmap_data <- heatmap_data %>%
  spread(Team, team_util_perc)

#Replace na values caused by teams not having an allocation
heatmap_data[is.na(heatmap_data)] <- 0


#order by date
heatmap_data <- subset( heatmap_data, select = -Date )



```


Summary Stats {data-orientation=rows}
=====================================  


Row
-----------------------------------------------------------------------

### Desk Total

```{r echo=FALSE, eval=TRUE}
valueBox(format(desk_total$n, big.mark=","), caption = "Total number of Desks", icon="fa-desktop")
```

### Staff Total

```{r}
valueBox(format(staff_total$n, big.mark=","), caption = "Total number of Staff", icon="fa-user")
```

### Teams Total

```{r}
valueBox(format(teams_total$staff, big.mark=","), caption = "Total number of teams", icon="fa-users")
```

Row
-----------------------------------------------------------------------

### Annual desk availability

```{r}
valueBox(format(total_available_desks_annual, big.mark=","), caption = "desks available in period")
```

###  Annual Desk Utilisation

```{r}
valueBox(format(toal_utilised_desks_annual, big.mark=","), caption= "desks utilised in period") 
```

### Annuafl desks unused
```{r}
valueBox(format(total_unused_desks_annual, big.mark=","), caption = "Unused desks in period")
```


Row
-----------------------------------------------------------------------

### Unique Visitors per year

```{r}
valueBox(format(unique_visitors_per_year$count, big.mark = ","), caption = "unique visitors in period", icon="fa-user-tie")
```


### Max Building Utilisation Date

```{r}
valueBox(max_utilisation_date, caption = "Max Utilisation Date", icon="fa-calendar-alt")
```

### Max Daily Building Utilisation

```{r}
gauge(max_utilisation_perc, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)))
```

Row
-----------------------------------------------------------------------

Explanation of the project and our approach goes here

Team Utilisation
=====================================  


Row
-----------------------------------------------------------------------
```{r}
#boxplot(x, data=heatmap_data$)

```


Model
=====================================  